# Generated by Django 2.0 on 2019-03-27 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=50)),
                ('date', models.DateField(null=True)),
                ('commit', models.TextField()),
                ('views', models.IntegerField(default=0)),
                ('document', models.FileField(upload_to='Event/')),
                ('uploaded_on', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'event_database',
                'ordering': ('date', 'title'),
                'managed': True,
            },
        ),
    ]
