# Generated by Django 2.0 on 2019-03-27 12:11

import any_urlfield.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventPhotos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', any_urlfield.models.fields.AnyUrlField(max_length=1000, verbose_name='URL')),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='event.Event')),
            ],
            options={
                'verbose_name_plural': 'Event Photos',
                'ordering': ('event', 'time'),
            },
        ),
    ]
