# Generated by Django 2.0 on 2019-03-27 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UpComingEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('date', models.DateField(null=True)),
                ('commit', models.TextField()),
                ('document', models.FileField(upload_to='img_upComingEvent/')),
                ('uploaded_on', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'event_upcoming_database',
                'ordering': ('date', 'uploaded_on'),
                'managed': True,
            },
        ),
    ]
